stages:
  data_ingestion:
    cmd: python src/ThyroidProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ThyroidProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/

  data_validation:
    cmd: python src/ThyroidProject/pipeline/stage_02_data_validation.py
    deps:
      - src/ThyroidProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema.yaml
    outs:
      - artifacts/data_validation/status.txt
  
  data_transformation:
    cmd: python src/ThyroidProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/ThyroidProject/pipeline/stage_03_data_transformation.py
      - src/ThyroidProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema.yaml
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv

  model_trainer:
    cmd: python src/ThyroidProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/ThyroidProject/pipeline/stage_04_model_trainer.py
      - artifacts/data_transformation/train.csv
      - config/config.yaml
      - schema.yaml
      - params.yaml
    params:
      - GradientBoostedTreesLearner
    outs:
      - artifacts/model_trainer/model
      - model


  model_evaluation:
    cmd: python src/ThyroidProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/ThyroidProject/pipeline/stage_05_model_evaluation.py
      - artifacts/data_transformation/test.csv
      - artifacts/model_trainer/model
      - config/config.yaml
      - schema.yaml
      - params.yaml
    params:
      - GradientBoostedTreesLearner
    outs:
      - artifacts/model_evaluation/metrics.html


  drift_monitoring:
    cmd: python src/ThyroidProject/pipeline/stage_06_drift_monitoring.py
    deps:
      - src/ThyroidProject/pipeline/stage_06_drift_monitoring.py
      - config/config.yaml
      - artifacts/model_trainer/model
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv
    outs:
      - artifacts/drift_monitoring/report.html
      - artifacts/drift_monitoring/test.html
      - drift_reports/report.html
      - drift_reports/test.html