name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub with PAT
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t tejas05in/tdpapp:latest .
          docker push tejas05in/tdpapp:latest